---
# Source: mongo/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "mern-app"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mongo
    helm.sh/chart: mongo-0.1.0

---
# Source: mongo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: mern-app
  labels:
    helm.sh/chart: mongo-0.1.0
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true

---
# Source: mongo/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: mern-app
  name: mongo-db-secret
type: Opaque
data:
  username: YWRtaW4=         #admin
  password: cGFzc3dvcmQxMjM= #password123
---
# Source: mongo/templates/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/kubernetes/mongodb"
---
# Source: mongo/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mern-app
spec:
  storageClassName: manual
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "800Mi"
---
# Source: mongo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: mern-app
  name: mongo
  labels:
    helm.sh/chart: mongo-0.1.0
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: http
      protocol: TCP
      name: mongo
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo

---
# Source: mongo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mern-app
  name: mongo
  labels:
    helm.sh/chart: mongo-0.1.0
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/instance: mongo
  template:
    metadata:
      labels:
        helm.sh/chart: mongo-0.1.0
        app.kubernetes.io/name: mongo
        app.kubernetes.io/instance: mongo
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: mongo
      containers:
        - name: mongo
          image: "mongo:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mongo-db-secret
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongo-db-secret
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - mongosh
              - --port
              - "27017"
              - --eval
              - db.adminCommand('ping')
              - --quiet
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
---
# Source: mongo/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "mongo-test-connection"
  labels:
    helm.sh/chart: mongo-0.1.0
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['mongo:27017']
  restartPolicy: Never

