apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.secretName }}
type: Opaque
data:
  username: YWRtaW4=         #admin
  password: cGFzc3dvcmQxMjM= #password123